version: '3'
services:
    node:
        image: "node:8"
        user: node
        depends_on:
            - database
        working_dir: /usr/src/app
        environment:
            - NODE_ENV=production
        volumes:
            - .:/usr/src/app
        ports:
            - "4000:4000"
        extra_hosts:
            - "serverhost:172.17.0.1"
        command: ["npm", "start"]
        networks:
            tsqnetwork:
                aliases:
                    - tsqapp
    database:
        image: "mongo:3.6"
        restart: always
        volumes:
            - "db-data:/data/db"
        ports:
            - "27018:27017"
        networks:
            tsqnetwork:
                aliases:
                    - tsqdb
volumes:
    db-data:
networks:
    tsqnetwork:
